package online.privacy;

import android.content.Context;

import junit.framework.Assert;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.Mock;
import org.mockito.Spy;
import org.powermock.api.mockito.PowerMockito;
import org.powermock.core.classloader.annotations.PrepareForTest;
import org.powermock.modules.junit4.PowerMockRunner;

import static org.mockito.Matchers.anyString;
import static org.mockito.Matchers.anyInt;
import static org.powermock.api.support.membermodification.MemberMatcher.method;

@RunWith(PowerMockRunner.class)
@PrepareForTest(PrivacyOnlineApiRequest.class)
public class PrivacyOnlineApiRequestTest {

    @Mock
    Context mockContext;

    // This three mocks are because JSON* is part of the Android implementation (android.jar) which
    // Unit tests replace with a shadow that has nothing in it. Ergo, we can't "create" an object
    // of that type. So we need to create mock versions of them.
    @Mock
    JSONObject apiResponse;

    @Mock
    JSONArray locationList;

    @Mock
    JSONObject locationItem;

    @Spy
    PrivacyOnlineApiRequest partialMockedRequest = new PrivacyOnlineApiRequest(mockContext);

    @Before
    public void setUp() throws Exception {
        PowerMockito.doReturn(apiResponse)
                .when(partialMockedRequest, method(PrivacyOnlineApiRequest.class, "makeAPIRequest", String.class, String.class, String.class))
                .withArguments(anyString(), anyString(), anyString());

        PowerMockito.doReturn(locationList)
                .when(apiResponse, method(JSONObject.class, "getJSONArray", String.class))
                .withArguments(anyString());

        PowerMockito.doReturn(locationItem)
                .when(locationList, method(JSONArray.class, "getJSONObject", int.class))
                .withArguments(anyInt());
        PowerMockito.doReturn(1)
                .when(locationList, method(JSONArray.class, "length"))
                .withNoArguments();

        PowerMockito.doReturn("Test Hostname")
                .when(locationItem, method(JSONObject.class, "getString", String.class))
                .withArguments("hostname");
        PowerMockito.doReturn("Test Label")
                .when(locationItem, method(JSONObject.class, "getString", String.class))
                .withArguments("label");
    }

    @Test
    public void verifyUserAccount_ok() throws Exception {

        // Mock the private method so we don't go to the API.
        // Check that verifyUserAccount() handles a "that's valid" response from the API.
        PowerMockito.doReturn("1")
                .when(apiResponse, method(JSONObject.class, "getString", String.class))
                    .withArguments(anyString());

        Assert.assertEquals(true, partialMockedRequest.verifyUserAccount("bert", "ernie"));
    }

    @Test
    public void verifyUserAccount_notOK() throws Exception {

        // Mock the private method so we don't go to the API.
        // Check that verifyUserAccount() handles a "lolnope" response from the API.
        PowerMockito.doReturn("0")
                .when(apiResponse, method(JSONObject.class, "getString", String.class))
                .withArguments(anyString());

        Assert.assertEquals(false, partialMockedRequest.verifyUserAccount("cannon", "ball"));
    }

    @Test
    public void verifyUserAccount_malformedJSONException() throws Exception {

        // Mock the private method so we don't go to the API.
        // Check that verifyUserAccount() handles a "ZOMGBADJSON!!!one" exception from the API data.
        PowerMockito.doThrow(new JSONException("FAIL"))
                .when(apiResponse, method(JSONObject.class, "getString", String.class))
                .withArguments(anyString());

        Assert.assertEquals(false, partialMockedRequest.verifyUserAccount("thelma", "louise"));
    }


    @Test
    public void getLocation_correctCount() throws Exception {

        int listTestLength = 3;

        // This overrides the Mock created in setUp()
        PowerMockito.doReturn(listTestLength)
                .when(locationList, method(JSONArray.class, "length"))
                .withNoArguments();

        Assert.assertEquals(listTestLength, partialMockedRequest.getLocationList().size());
    }

    @Test
    public void getLocation_correctTranslation() throws Exception {

        // Check we get the correct hostname and label for an entry as it was in the JSON.
        Assert.assertEquals("Test Hostname", partialMockedRequest.getLocationList().get(0).getHostname());
        Assert.assertEquals("Test Label", partialMockedRequest.getLocationList().get(0).getLabel());
    }

    @Test
    public void getLocation_malformedJSONException() throws Exception {

        // Make sure we handle the Exception generated by duff data
        PowerMockito.doThrow(new JSONException("FAIL"))
                .when(apiResponse, method(JSONObject.class, "getJSONArray", String.class))
                .withArguments(anyString());

        Assert.assertEquals(null, partialMockedRequest.getLocationList());
    }
}